version: '3.9'

services:
  springboot-app:
    build:
      context: .
      dockerfile: Dockerfile
    image: docker-spring-boot
    container_name: my-docker-spring-boot
    ports:
      - "8080:8080"
    networks:
      - prometheus-grafana-network
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    healthcheck:
      test: [ "CMD", "curl", "--fail", "http://localhost:8080/actuator/health" ]
      interval: 30s
      timeout: 5s
      retries: 3
    volumes:
      - ./grafana-spring-boot/code:/app
      - ./grafana-spring-boot/config:/config
    command: [ "java", "-jar", "docker-spring-boot.jar" ]

  prometheus:
    image: prom/prometheus
    container_name: prometheus_container
    ports:
      - "9090:9090"
    volumes:
      - ./config/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./config/prometheus/rules:/etc/prometheus/rules
    networks:
      - prometheus-grafana-network

  grafana:
    image: grafana/grafana
    container_name: grafana-container
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    networks:
      - prometheus-grafana-network
    volumes:
      - ./config/grafana/provisioning:/etc/grafana/provisioning
      - ./config/grafana/dashboards:/var/lib/grafana/dashboards

networks:
  prometheus-grafana-network:
    driver: bridge